config/routes.rb
Rails.application.routes.draw do
  root'domains#summary'
  get 'domains/scans'
  get 'domains/scanonedomain'
  get 'domains/sipscan'
  get 'domains/mxscan'
  get 'domains/csvprocess'
  get 'domains/summary'
  get 'domains/test'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  resources :domains

end

app/models/domain.rb
class Domain < ActiveRecord::Base
   
   validates :domain, presence: true 
   def self.search(search)
   where("domain LIKE ? OR spf LIKE ? OR dmarc LIKE ?  OR txt LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
   end
   scope :forces, -> { where(txt: 'force') }
   scope :spf, -> { where.not(spf: "")}
   scope :dmarc, -> { where.not(dmarc: "")}
   scope :sip, -> { where.not(sip: "")}
   scope :mx, -> { where.not(mx: "")}
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_filter :authorize
  before_action :set_domain, only: [:show, :edit, :update, :destroy,]
  helper_method :sort_column, :sort_direction
  def index
        @domains = Domain.order("domain ASC")
          if params[:search]
           @domains = Domain.search(params[:search]).order("domain ASC")
          else
          @domains = Domain.all.order("domain ASC")
          end
  end
  
  def scans
    
  end
  
  def csvprocess
    @domains = Domain.all
  end
  
  def mxscan
     @domains = Domain.all
  end
  def sipscan
     @domains = Domain.all
  end

  def test 
     @domains = Domain.all
  end
  def summary
    
          @domains = Domain.all.paginate(page: params[:page], per_page: 20).order("#{sort_column} #{sort_direction}")
          @doms = Domain.all
          if params[:search]
          @domains = Domain.all.paginate(page: params[:page], per_page: 20).search(params[:search]).order("#{sort_column} #{sort_direction}")
          else
          @domains = Domain.all.paginate(page: params[:page], per_page: 20).order("#{sort_column} #{sort_direction}")
          end
  end
  
  def scanonedomain
     @domains = Domain.all
          if params[:search]
           @domains = Domain.search(params[:search]).order("domain ASC")
          else
          @domains = Domain.all.order("domain ASC")
          end
     
  end
  
  

  # GET /domains/1
  # GET /domains/1.json
  def show
    @domain = Domain.find(params[:id])
  end
  
  
  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
    
     
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:domain, :spf, :dmarc, :mx, :txt, :sip)
    end
    
    def domainupdate_params
      params.permit(:domain, :spf, :dmarc, :txt, :mx, :sip)
    end
  
  
    def sortable_columns
    ["Domain", "Spf", "DMARC", "MX", "SIP"]
    end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "Domain"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  

end

app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb

class SessionsController < ApplicationController

   def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
   end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb

class UsersController < ApplicationController
    def new
    end

    def create
        user = User.new(user_params)
        if user.save
          session[:user_id] = user.id
          redirect_to '/'
        else
          redirect_to '/signup'
        end
    end
end   

private 
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/domains_helper.rb
module DomainsHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                    <div class="field">
                      <%= f.label :domain %><br>
                      <%= f.text_field :domain, :size => 50 %>
                    </div>
                    <div class="field">
                      <%= f.label :spf %><br>
                      <%= f.text_field :spf, :size => 50 %>
                    </div>
                    <div class="field">
                      <%= f.label :dmarc%><br>
                      <%= f.text_field :dmarc, :size => 50 %>
                    </div>
                    <div class="field">
                      <%= f.label :mx%><br>
                      <%= f.text_field :mx, :size => 50 %>
                    </div>

                    <div class="field">
                      <%= f.label :txt%><br>
                      <%= f.text_field :txt, :size => 50  %>
                    </div>
                    <div class="field">
                      <%= f.label :sip%><br>
                      <%= f.text_field :sip, :size => 50  %>
                    </div>
                    <div class="actions">
                      <%= f.submit class: 'btn btn-primary' %>
                      <%= link_to "Cancel", domains_path, class: "btn btn btn-danger" %>

                    </div>
                  <% end %>
            </div>
          </div>
        </div>  
        </div>

app/views/domains/csvprocess.html.erb
<% require 'csv' %>
<% CSV.foreach("./tmp/domains.csv") do |row|%>

<%row = row[0]%>
<p><%= row%></p>
<%  object = Domain.new(:domain => row) %>
<%  object.save %>

<%end%>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form' %>
<%= link_to 'Scan', domains_scanonedomain_path %> |
<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Domains</h1>


    <% @domains.each do |domain| %>
     <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                 <%= link_to domain.domain, domain_path(domain)%>
                </div>
                <div class="article-body">
                  <p><strong>Sender Policy Framework Record</strong></p>
                  <% if domain.spf.present? %>
                 <p style="background-color:rgb(0,255,0)"><%= domain.spf %></p>
                 <% else %>
                 <p style="color:#ff0000" >None</p>
                 <%end%>
                 </div>
                 <div class="article-body">
                  <p><strong>DMARC Record</strong></p>
                     <% if domain.dmarc.present? %>
                     <p style="background-color:rgb(0,255,0)"><%= domain.dmarc %></p>
                     <% else %>
                     <p style="color:#ff0000">None</p>
                     <%end%>
                 </div>
                 <div class="article-body">
                  <p><strong>MX Record</strong></p>
                     <% if domain.mx.present? %>
                     <p style="background-color:rgb(0,255,0)"><%= domain.mx %></p>
                     <% else %>
                     <p style="color:#ff0000">None</p>
                     <%end%>
                 </div>

                 <div class="article-body">
                  <p><strong>Sip Record</strong></p>
                      <% if domain.sip.present? %>
                      <p style="background-color:rgb(0,255,0)"><%= domain.sip %></p>
                      <% else %>
                     <p style="color:#ff0000">None</p>
                     <%end%>
                 </div>
                
                <div class="article_actions">
                    <%= link_to "Edit this Record", edit_domain_path(domain), class: "btn btn-xs btn-primary" %>
                    <%= link_to "Delete Record", domain_path(domain), method: :delete, data: {confirm: "Are You Sure" }, class: "btn btn-xs btn-danger" %>
                </div>
            </div>
        </div> 
    </div>
    <% end %>
        

<br>

<%= link_to 'New Domain', new_domain_path %>
<%= link_to 'Run Scan', domains_scans_path %>

app/views/domains/mxscan.html.erb
<h1>Domain sip scan</h1>
<p>RUNNING</p>

    <% @domains.each do |domain| %>
    <% mxdomain = domain.domain %>
        <% next if mxdomain =="askthe.police.uk" %>
            <% next if mxdomain =="southwales.police.uk" %>
            <% next if mxdomain =="south-wales.police.uk" %>
            
            <p><%= mxdomain %>
                <%begin%>
                <% result = Resolv::DNS.open.getresources(mxdomain, Resolv::DNS::Resource::IN::MX) %>
                <% if result !="" %>
                <% strval = result.map { |r| [IPSocket::getaddress(r.exchange.to_s) ]} %>
                <%else%>
                <% strval ="" %>
                <% end%>
                <%rescue%>
                <p>something broke</p>
                <%break%>
                <%end%>
            <% strval = strval.join (",") %>
            <%= strval%>

        <% domain.update_attribute(:mx, strval) %>

           
    <% end %></p>     

<P>COMPLETE</P>
     
<%= link_to 'Show Domain', domains_path %>
<%= link_to 'Run Scan', domains_scans_path %> 

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/domains/scanonedomain.html.erb
<h1>Domain Update scan</h1>
<p>RUNNING</p>

     <% Resolv::DNS.open do |dns| %>
        <% @domains.each do |domain| %>
        <%= domain %>
         <% host = domain.domain %>
         <%   records = dns.getresources(host, Resolv::DNS::Resource::IN::TXT) %>
            <% records.each do |record| %>
            <% txt = record.strings.join %>
            
                <% if txt.include?('v=spf1')%>
                  <% domain.update_attribute(:spf, txt) %>
                  <% domain.save %>
                <% end %>
            <% end %>
                 <% hostd = "_dmarc.#{host}" %>
                 <%= hostd%>
                 <% recordds = dns.getresources(hostd, Resolv::DNS::Resource::IN::TXT) %>
                <% recordds.each do |recordd| %>
                 <% txtd = recordd.strings.join %>
                 <%= txtd %>
                  <% if txtd.include?('v=DMARC1;')%>
                  <% domain.update_attribute(:dmarc, txtd) %>
                  <% domain.save %>
                  <% end %>
                <% end %>
        <% end %>     
     <% end %>
 <p>Finished</p>             
 <%= link_to 'Show Domain', domains_path %>
<%= link_to 'Run Scan', domains_scans_path %>                    
          
          
            
          

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                 <%= @domain.domain %>
                </div>
                <div class="article-body">
                  <p><strong>Sender Policy Framework Record</strong></p>
                  <% if @domain.spf !="" %>
                 <%= @domain.spf %>
                 <% else %>
                 <p>None</p>
                 <%end%>
                 </div>
                 <div class="article-body">
                  <p><strong>DMARC Record</strong></p>
                     <% if @domain.dmarc !="" %>
                     <%= @domain.dmarc %>
                     <% else %>
                     <p>None</p>
                     <%end%>
                 </div>
                 <div class="article-body">
                  <p><strong>MX Record</strong></p>
                     <% if @domain.mx !="" %>
                     <%= @domain.mx %>
                     <% else %>
                     <p>None</p>
                     <%end%>
                 </div>
                 <div class="article-body">
                  <p><strong>txt Record</strong></p>
                     <% if @domain.txt !="" %>
                     <%= @domain.txt %>
                     <% else %>
                     <p>None</p>
                     <%end%>
                 </div>
                 <div class="article-body">
                  <p><strong>Sip Record</strong></p>
                      <% if @domain.sip !="" %>
                      <%= @domain.sip %>
                      <% else %>
                     <p>None</p>
                     <%end%>
                 </div>
                
                <div class="article_actions">
                    <%= link_to "Edit this Record", edit_domain_path(@domain), class: "btn btn-xs btn-primary" %>
                    <%= link_to "Delete Record", domain_path(@domain), method: :delete, data: {confirm: "Are You Sure" }, class: "btn btn-xs btn-danger" %>
                </div>
            </div>
        </div> 
    </div>

app/views/domains/sipscan.html.erb
<h1>Domain sip scan</h1>
<p>RUNNING</p>

    <% @domains.each do |domain| %>
    <% sipdomain = "sip." + domain.domain %>
    <p><%= sipdomain %>
        <% result = Net::DNS::Resolver.start(sipdomain , Net::DNS::A) %>
        <% values = result.each_mx %>
        <% values.each do |value| %>
        <% strval = "#{value}" %>
        <% sipip = strval.partition('A').last %>
        <%= sipip %>
        <% domain.update_attribute(:sip, sipip) %>
        <% end %>
    <% end %></p>     
                      
         
                 
            
 

<P>COMPLETE</P>
     
<%= link_to 'Show Domain', domains_path %>
<%= link_to 'Run Scan', domains_scans_path %> 

app/views/domains/summary.html.erb
<p id="notice"><%= notice %></p>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip(); 
});
</script>

<h1>Domains</h1>

     <div class="row">
        <div class="col-xs-offset=0">
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th class="col-xs-4"><%= sort_link "Domain" %></th>
                  <th class="col-xs-2"><%= sort_link "Spf" %></th>
                  <th class="col-xs-2"><%= sort_link "DMARC" %></th>
                  <th class="col-xs-2"><%= sort_link "MX" %></th>
                  <th class="col-xs-2"><%= sort_link "SIP" %></th>
                </tr>
              </thead
             <% @domains.each do |domain| %>

              <tbody>
                <tr>
                 <td><%= link_to domain.domain, edit_domain_path(domain),:target => "_blank" %></td>
                  
                     <%if domain.spf.present? %>
                      <td><a href="#" data-toggle="tooltip" title="<%= domain.spf %>">SPF Present</a> </td>
                      <% else%>
                      <td> </td>
                      <% end %>
                <%if domain.dmarc.present? %>
                      <td><a href="#" data-toggle="tooltip" title="<%= domain.dmarc %>">DMARC Present</a> </td>
                      <% else%>
                      <td> </td>
                      <% end %> 
                <%if domain.mx.present? %>
                      <td><a href="#" data-toggle="tooltip" title="<%= domain.mx %>">MX Present</a> </td>
                      <% else%>
                      <td> </td>
                      <% end %> 
                <%if domain.sip.present? %>
                      <td><a href="#" data-toggle="tooltip" title="<%= domain.sip %>">Sip Present</a> </td>
                      <% else%>
                      <td> </td>
                      <% end %>
                         
                </tr>
               
              </tbody>
               <%end%>
               <tr>
                   <td>Total Force Domains = <%= Domain.forces.count%></td>
                   <td>Total SPF records = <%= Domain.forces.spf.count(:conditions  => ["spf like ?","%a:mail-outbound%"]) %>   </td>
                   <td>Total DMARC records = <%=  Domain.forces.dmarc.length %></td>
                   <td>Total MX records = <%=  Domain.forces.mx.length %></td>
                   <td>Total SIP records = <%=  Domain.forces.sip.length %></td>


               </tr>
            </table>
            <div class = center><%= will_paginate @domains %></div>

</div>
</div>

app/views/domains/test.html.erb
<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip({
        placement : 'top'
    });
});
</script>
<h1>Statistics</h1>
 <table class="table table-striped">
    <tr>
        <td>
         Number of Police Domains  (includes .police.uk and pnn.police.uk)
   
        </td>
        <td>
            <%= Domain.ids.length %>
        </td>
        <td><a class="btn btn-success btn-sm btn-block btn-block">
          <span class="glyphicon glyphicon-record" style="color:green" data-toggle="tooltip" data-original-title="Unchanged"></span> Unchanged 
        </a></td>
        <td></td>
    </tr>
    
    <tr>
        <td>
         Number of Police Domains with SPF records 
   
        </td>
        <td>
            <%= Domain.spf.length %>
        </td>
        <td><a class="btn btn-danger btn-sm btn-block">
          <span class="glyphicon glyphicon-record" style="color:red" data-toggle="tooltip" data-original-title="Unchanged"></span> Unchanged 
        </a></td>
        <td>3 to update</td>

    </tr>
     
    <tr>
        <td>
          Number of Police Domains with SPF records with the old pnn gateway listed 
  
        </td>
        <td>
            <%= Domain.spf.where("spf like?", ["%a:mail%"]).length %>
        </td>
        <td><a class="btn btn-success btn-sm btn-block">
          <span class="glyphicon glyphicon-minus" style="color:green" data-toggle="tooltip" data-original-title="Down 7"></span>    Down 7    
        </a></td>
        <td>55 to update</td>

    </tr>
     
    <tr>
        <td>
          Number of Police Domains with DMARC records 
  
        </td>
        <td>
            <%= Domain.dmarc.length %>
        </td>
        <td><a class="btn btn-success btn-sm btn-block">
          <span class="glyphicon glyphicon-plus" style="color:green" data-toggle="tooltip" data-original-title="Up 9"></span>    Up 9    
        </a></td>
        <td>420 to update</td>

    </tr>
     <tr> </tr>
    <tr>
        <td>
            Number of Police Domains with DMARC record set to reject</td>
        <td> <%=Domain.dmarc.where("dmarc like?",["%reject%"]).length %>
        </td>
        <td><a class="btn btn-success btn-sm btn-block" data-toggle="tooltip" data-original-title="Up 1">
          <span class="glyphicon glyphicon-plus" style="color:green" ></span>    Up 1    
        </a></td>
        <td>469 to update</td>

    </tr>
    <tr>
        <td>
            Number of Force Domains with SPF records (Just pnn.police.uk domains)

        </td>
        <td>
            <%= Domain.forces.spf.length %>
        </td>
        <td><a class="btn btn-warning btn-sm btn-block">
          <span class="glyphicon glyphicon-record" style="color:green" data-toggle="tooltip" data-original-title="Unchanged"></span> Unchanged 
        </a></td>
        <td>Complete</td>

    </tr>
     
    <tr>
        <td>
           Number of Force Domains with SPF records with the old pnn gateway listed 
 
        </td>
        <td>
            <%= Domain.forces.spf.where("spf like?", ["%a:mail%"]).length %>
        </td>
        <td><a class="btn btn-success btn-sm btn-block">
          <span class="glyphicon glyphicon-minus" style="color:green" data-toggle="tooltip" data-original-title="Down 1"></span>    Down 1    
        </a></td>
        <td>52 to update (2 on CJX)</td>

    </tr>
     
    <tr>
        <td>
            Number of Force Domains with DMARC records 

        </td>
        <td>
            <%= Domain.forces.dmarc.length %>
        </td>
        <td><a class="btn btn-success btn-sm btn-block">
          <span class="glyphicon glyphicon-plus" style="color:green" data-toggle="tooltip" data-original-title="Up 9"></span>    Up 9   
        </a></td>
        <td>45 to update</td>

    </tr>
     
    <tr>
        <td>
          Number of Force Domains with DMARC record set to reject
  
        </td>
        <td>
            <%= Domain.forces.dmarc.where("dmarc like?", ["%reject%"]).length %>
        </td>
        <td><a class="btn btn-danger btn-sm btn-block"data-toggle="tooltip" data-original-title="Only one domain will prevent spam">
          <span class="glyphicon glyphicon-record" style="color:red" data-toggle="tooltip" data-original-title="Unchanged"></span> Unchanged 
        </a></td>
        <td>74 to update</td>

    </tr>
</table>

app/views/layouts/_footer.html.erb
<div container>
    <footer class:"center footer">
      <small>
          Police Domain Reporting Tool Version 1.0 COPYRIGHT &copy TDCOM Computers 
      </small>  
        <nav>
            <ul>
                <li><%= link_to "Report", domains_path %></li>
            </ul>
        </nav>
    </footer>
    
    
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}"%>' >
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
    </div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Domain Reporting", domains_path, class: "navbar-brand", id: "logo" %>
    </div>

    
        
      <form class="navbar-form navbar-right">
        <div class="form-group">
            <%= form_tag(domains_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search" %>
            <%= submit_tag "Search", :name => nil %>
            <% end %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
     <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Summary Report", domains_summary_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Summary Forces Report", domains_summary_path(search: "force") %></li>
            <li role="separator" class="divider"></li>

            <li><%= link_to "Detailed Report", domains_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Add Domain", new_domain_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Edit Domains", domains_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Run Scan", domains_scanonedomain_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Run Sip Scan", domains_sipscan_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Run MX Scan", domains_mxscan_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Police Domain Reporting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<div class="container">
  <%= yield %>

</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->

<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>